Repository projetoKhali/api4back, pull requests merged in 2024-06, with the labels that each got.

#70 fix: track_view
  db/postgres-func.sql
  db/postgres_functions.sql
  db/postgres_views.sql
  makefile
  src/main/java/com/fatec/springapi4/entity/TrackMetrics.java
Labels: bug, DB

#79 fix: `allPartnerReports` pagination
  db/3_postgres_views.sql
  src/main/java/com/fatec/springapi4/controller/PartnerReportsController.java
  src/main/java/com/fatec/springapi4/entity/PartnerReports.java
  src/main/java/com/fatec/springapi4/repository/PartnerReportsRepository.java
  src/main/java/com/fatec/springapi4/repository/PartnerRepository.java
  src/main/java/com/fatec/springapi4/repository/TrackRepository.java
  src/main/resources/application.properties
Labels: bug, Repository, Entity, Controller, Partner, Track, DB

#80 fix partner metrics
  db/3_postgres_views.sql
  src/main/java/com/fatec/springapi4/Validation.java
Labels: bug
